<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id'                => 2,
                'name'              => 'BOOTY BEI LOW RISE SKINNY BOOTCUT JEANS',
                'slug'              => 'booty-bei-low-rise-skinny-bootcut-jeans',
                'short_description' => "Can't help it. If it's not low-waist, I don't want it. Slim, hip-hugging, leg-lengthening jeans with that iconic bootcut flick. Soft, stretchy denim, a subtle flare, and five-pocket nostalgia. Just… hot.",
                'description'       => "Can't help it. If it's not low-waist, I don't want it. The signature slim, hip-hugging, leg-lengthening jeans with that trippin' bootcut flick (baddie, hi). Designed to sit low in all the right places while sculpting your silhouette with a soft, stretchy denim blend that moves with you, not against you. Featuring a subtle flare that elongates the legs, vintage-inspired five-pocket detailing for that nostalgic Y2K energy, and partially recycled fabric because looking hot and doing better can coexist. Effortless from daytime errands to midnight plans — these jeans were made for tiny tops, oversized shades, confident walks, and main-character moments. Just… ridiculously hot.",
                'regular_price'     => 49.99,
                'sale_price'        => null,
                'SKU'               => 'WC-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779348528.jpg',
                'images'            => '1779348675-1.jpg,1779348675-2.jpg,1779348675-3.jpg,1779348675-4.jpg',
                'category_id'       => 1,
                'brand_id'          => 2,
                'created_at'        => '2026-05-21 00:28:48',
                'updated_at'        => '2026-05-21 00:31:17',
            ],
            [
                'id'                => 3,
                'name'              => 'MESSY LOW RISE REGULAR STRAIGHT JEANS',
                'slug'              => 'messy-low-rise-regular-straight-jeans',
                'short_description' => 'Messy jeans have a regular fit with a low waist, straight leg and long length. These jeans are crafted from rigid cotton denim enhanced with recycled cotton, featuring a classic 5-pocket design and a zip fly.',
                'description'       => 'Messy Jeans feature a relaxed regular fit with a low-rise waist, straight-leg silhouette, and extra-long length for an effortlessly cool look. Crafted from rigid cotton denim blended with recycled cotton, they offer a structured vintage feel while supporting a more conscious approach to fashion. Designed with a classic 5-pocket construction, zip fly closure, and timeless denim detailing, these jeans are perfect for everyday styling with an edgy, laid-back attitude.',
                'regular_price'     => 49.99,
                'sale_price'        => null,
                'SKU'               => 'WC-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779349331.jpg',
                'images'            => '1779349331-1.jpg,1779349331-2.jpg,1779349331-3.jpg,1779349331-4.jpg,1779349331-5.jpg',
                'category_id'       => 1,
                'brand_id'          => 2,
                'created_at'        => '2026-05-21 00:42:13',
                'updated_at'        => '2026-05-21 00:42:13',
            ],
            [
                'id'                => 4,
                'name'              => 'ROSABEL LOW RISE LOOSE LACE-TRIM BLOOMERS',
                'slug'              => 'rosabel-low-rise-loose-lace-trim-bloomers',
                'short_description' => 'Low-rise lace bloomers with a loose fit, drawstring waist, and adjustable scrunched hems.',
                'description'       => "A pair of low-rise, loosey-lacey bloomers that just rests on the hip, like I don't care but I do, I really do. They've got an easy elastic drawstring waistband, plus side pockets for tiny treasures. The three-quarter legs finish in wide, lace-trimmed hems with their own drawstrings, personalise the scrunch depending on the mood. Romantic pirate, little bit mischievous. Very me.",
                'regular_price'     => 59.99,
                'sale_price'        => 49.99,
                'SKU'               => 'WC-003',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779350102.jpg',
                'images'            => '1779350102-1.jpg,1779350102-2.jpg,1779350102-3.jpg,1779350102-4.jpg,1779350102-5.jpg,1779350102-6.jpg',
                'category_id'       => 1,
                'brand_id'          => 3,
                'created_at'        => '2026-05-21 00:55:05',
                'updated_at'        => '2026-05-21 00:55:05',
            ],
            [
                'id'                => 5,
                'name'              => 'EMBROIDERED KNEE LENGTH COTTON SHORTS',
                'slug'              => 'embroidered-knee-length-cotton-shorts',
                'short_description' => 'Low-waist embroidered jorts with a loose fit, elastic waistband, side pockets, and eyelet details.',
                'description'       => 'Embroidered cotton shorts in a classic knee length jorts cut, with a low waist and a loose fit. The relaxed silhouette falls easy through the leg with a pull-on construction and a full elastic waistband. Finished with broderie anglais style eyelet embroidery, side pockets and rounded, embroidered bottom hems.',
                'regular_price'     => 69.99,
                'sale_price'        => null,
                'SKU'               => 'WC-004',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779351913.jpg',
                'images'            => '1779351913-1.jpg,1779351913-2.jpg,1779351913-3.jpg,1779351913-4.jpg,1779351913-5.jpg',
                'category_id'       => 1,
                'brand_id'          => 3,
                'created_at'        => '2026-05-21 01:25:15',
                'updated_at'        => '2026-05-21 01:25:15',
            ],
            [
                'id'                => 6,
                'name'              => 'RECYCLED DOWN PUFFER JACKET',
                'slug'              => 'recycled-down-puffer-jacket',
                'short_description' => 'Oversized nylon puffer jacket with recycled padding, a 2-way zipper, roomy pockets, and a warm stand collar.',
                'description'       => 'An oversized nylon puffer jacket crafted from a soft recycled polyamide, padded with recycled down for ultimate warmth. This go-to puffer features a stand collar, a sturdy versatile 2-way zipper, Velcro placket, roomy side seam pockets, and two inner pockets.',
                'regular_price'     => 290.00,
                'sale_price'        => null,
                'SKU'               => 'WC-005',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779352071.jpg',
                'images'            => '1779352071-1.jpg',
                'category_id'       => 1,
                'brand_id'          => 4,
                'created_at'        => '2026-05-21 01:27:51',
                'updated_at'        => '2026-05-21 01:27:51',
            ],
            [
                'id'                => 7,
                'name'              => 'LOW RISE BAGGY PULL-ON TROUSERS',
                'slug'              => 'low-rise-baggy-pull-on-trousers',
                'short_description' => 'Low-rise pull-on trousers in washed cotton with a loose fit, drawstring waist, and seam detailing.',
                'description'       => 'A pair of loose-fitting pull-on trousers with a low rise, crafted from washed cotton. Designed with an elasticated drawstring waistband, slanted side pockets, and leg seam detailing for a structured look.',
                'regular_price'     => 84.99,
                'sale_price'        => null,
                'SKU'               => 'WC-006',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 10,
                'image'             => '1779352206.jpg',
                'images'            => '1779352206-1.jpg,1779352206-2.jpg',
                'category_id'       => 1,
                'brand_id'          => 4,
                'created_at'        => '2026-05-21 01:30:07',
                'updated_at'        => '2026-05-21 01:30:07',
            ],
            [
                'id'                => 8,
                'name'              => 'RUCHED HALTER MINI DRESS',
                'slug'              => 'ruched-halter-mini-dress',
                'short_description' => 'Slim-fit halter mini dress in soft jersey with a V-neckline, gathered seams, and an asymmetric hem.',
                'description'       => 'A slim-fit halter mini dress crafted from soft viscose jersey. Designed with a V-neckline, gathered centre front and back seams, and an asymmetric hemline.',
                'regular_price'     => 42.99,
                'sale_price'        => null,
                'SKU'               => 'WDR-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 7,
                'image'             => '1779353871.jpg',
                'images'            => '1779353871-1.jpg,1779353871-2.jpg,1779353871-3.jpg,1779353871-4.jpg,1779353871-5.jpg',
                'category_id'       => 4,
                'brand_id'          => 3,
                'created_at'        => '2026-05-21 01:57:53',
                'updated_at'        => '2026-05-21 01:57:53',
            ],
            [
                'id'                => 9,
                'name'              => 'SLEEVELESS BALLOON MINI DRESS',
                'slug'              => 'sleeveless-balloon-mini-dress',
                'short_description' => 'Sleeveless mini dress in a lightweight lyocell blend with a voluminous silhouette and gathered details.',
                'description'       => 'A sleeveless mini dress with a voluminous silhouette. Crafted from a lightweight lyocell blend, it features adjustable spaghetti straps, gathered detailing at the neckline and hem, and a double-layered construction for added volume.',
                'regular_price'     => 69.99,
                'sale_price'        => null,
                'SKU'               => 'WDR-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779354043.jpg',
                'images'            => '1779354043-1.jpg,1779354043-2.jpg,1779354043-3.jpg,1779354043-4.jpg,1779354043-5.jpg',
                'category_id'       => 4,
                'brand_id'          => 3,
                'created_at'        => '2026-05-21 02:00:46',
                'updated_at'        => '2026-05-21 02:00:46',
            ],
            [
                'id'                => 10,
                'name'              => 'SHORT-SLEEVED MINI T-SHIRT DRESS',
                'slug'              => 'short-sleeved-mini-t-shirt-dress',
                'short_description' => 'Stretchy cotton T-shirt mini dress with a cinched waist, soft pleats, and a raw-edge hem.',
                'description'       => 'A short T-shirt dress with a cinched silhouette. Crafted from stretchy cotton jersey, it features short sleeves and placed pleats at the waist for a softly gathered effect. Finished with a raw-edge hem and classic crew neckline.',
                'regular_price'     => 48.00,
                'sale_price'        => null,
                'SKU'               => 'WDR-003',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779354182.jpg',
                'images'            => '1779354182-1.jpg,1779354182-2.jpg,1779354182-3.jpg,1779354182-4.jpg,1779354182-5.jpg',
                'category_id'       => 4,
                'brand_id'          => 4,
                'created_at'        => '2026-05-21 02:03:05',
                'updated_at'        => '2026-05-21 02:03:05',
            ],
            [
                'id'                => 11,
                'name'              => 'SHEER LONG-SLEEVED V-NECK MAXI DRESS',
                'slug'              => 'sheer-long-sleeved-v-neck-maxi-dress',
                'short_description' => 'Semi-sheer maxi dress in lightweight dobby fabric with a deep V-neckline and flared sleeves.',
                'description'       => 'A semi-sheer maxi dress with a fluid drape. Crafted from lightweight dobby fabric, it features a deep V-neckline, long flared sleeves and slits at the side seams for easy movement.',
                'regular_price'     => 69.00,
                'sale_price'        => null,
                'SKU'               => 'WDR-004',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 6,
                'image'             => '1779354336.jpg',
                'images'            => '1779354336-1.jpg,1779354336-2.jpg,1779354336-3.jpg,1779354336-4.jpg',
                'category_id'       => 4,
                'brand_id'          => 4,
                'created_at'        => '2026-05-21 02:05:38',
                'updated_at'        => '2026-05-21 02:05:38',
            ],
            [
                'id'                => 12,
                'name'              => 'SLEEVELESS GATHERED JERSEY TOP',
                'slug'              => 'sleeveless-gathered-jersey-top',
                'short_description' => 'Slim-fit sleeveless jersey top with gathered side seams, flatlock details, and a soft ruched effect.',
                'description'       => 'A sleeveless top with a slim fit and soft stretch. Crafted from stretchy jersey, it features flatlock seams and gathered detailing along the side seams for a softly ruched effect. Finished with raglan-style armholes and a round neckline.',
                'regular_price'     => 24.99,
                'sale_price'        => null,
                'SKU'               => 'WMT-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779780982.jpg',
                'images'            => '1779780982-1.jpg,1779780982-2.jpg,1779780982-3.jpg,1779780982-4.jpg,1779780982-5.jpg',
                'category_id'       => 2,
                'brand_id'          => 3,
                'created_at'        => '2026-05-26 00:36:24',
                'updated_at'        => '2026-05-26 00:36:24',
            ],
            [
                'id'                => 13,
                'name'              => 'BELLE B RUCHED V-NECK CARDIGAN',
                'slug'              => 'belle-b-ruched-v-neck-cardigan',
                'short_description' => 'Soft, stretchy ruched cardigan top with a deep V-neckline, loop-button front, and a body-hugging fit.',
                'description'       => "This one knows it's cute. Soft, stretchy cotton that clings in all the right places and refuses to be subtle. The V-neck dips just enough and the looped button front keeps it interesting. Worn loose. A little skin, on purpose. Then the ruching hits, pulling everything in, turning \"simple cardi\" into main-character behaviour. Fun!",
                'regular_price'     => 29.99,
                'sale_price'        => null,
                'SKU'               => 'WMT-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779781153.jpg',
                'images'            => '1779781153-1.jpg,1779781153-2.jpg,1779781153-3.jpg,1779781153-4.jpg',
                'category_id'       => 2,
                'brand_id'          => 3,
                'created_at'        => '2026-05-26 00:39:15',
                'updated_at'        => '2026-05-26 00:39:15',
            ],
            [
                'id'                => 14,
                'name'              => 'FLANNEL BOXER SHORTS',
                'slug'              => 'flannel-boxer-shorts',
                'short_description' => 'Soft flannel boxer shorts with a loose fit, elastic waistband, and slanted side pockets.',
                'description'       => "A pair of soft flannel boxer shorts cut to a loose fit. They feature an elasticated waistband and slanted side pockets.\r\nLoose fit.\r\nShort length.\r\nRegular waist.\r\nElasticated waist.\r\nSlanted pockets.",
                'regular_price'     => 29.99,
                'sale_price'        => null,
                'SKU'               => 'WMP-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779781352.jpg',
                'images'            => '1779781352-1.jpg',
                'category_id'       => 6,
                'brand_id'          => 3,
                'created_at'        => '2026-05-26 00:42:33',
                'updated_at'        => '2026-05-26 00:42:33',
            ],
            [
                'id'                => 15,
                'name'              => '3-PACK SOUL MICRO BRAZILIAN BOTTOMS',
                'slug'              => '3-pack-soul-micro-brazilian-bottoms',
                'short_description' => '3-pack micro Brazilian bottoms in soft stretchy fabric with smooth edges and a seamless feel.',
                'description'       => "A 3-pack of minimal coverage, almost seamless micro brazilian-cut bottoms crafted from a soft stretchy fabric. These go-to's have smooth edges and a cotton lined gussets.",
                'regular_price'     => 30.00,
                'sale_price'        => 16.00,
                'SKU'               => 'WMP-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779781457.jpg',
                'images'            => '1779781457-1.jpg,1779781457-2.jpg,1779781457-3.jpg',
                'category_id'       => 6,
                'brand_id'          => 4,
                'created_at'        => '2026-05-26 00:44:19',
                'updated_at'        => '2026-05-26 00:44:19',
            ],
            [
                'id'                => 16,
                'name'              => '2-PACK RIBBED BRAZILIAN BRIEFS',
                'slug'              => '2-pack-ribbed-brazilian-briefs',
                'short_description' => '2-pack ribbed cotton Brazilian briefs with a mid-rise fit, soft stretch, and smooth elastic edges.',
                'description'       => 'A two pack of Brazilian briefs crafted from stretchy ribbed cotton. Designed with a mid-rise fit and clean elastic edges for a smooth, comfortable feel against the skin. Finished with a minimal silhouette that sits lightly on the body for everyday wear.',
                'regular_price'     => 19.99,
                'sale_price'        => null,
                'SKU'               => 'WMP-003',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 1,
                'image'             => '1779781560.jpg',
                'images'            => '1779781560-1.jpg,1779781560-2.jpg,1779781560-3.jpg',
                'category_id'       => 6,
                'brand_id'          => 4,
                'created_at'        => '2026-05-26 00:46:02',
                'updated_at'        => '2026-05-26 00:46:02',
            ],
            [
                'id'                => 17,
                'name'              => 'Court Spec 2 Tennis Shoes',
                'slug'              => 'court-spec-2-tennis-shoes',
                'short_description' => 'Lightweight all-court tennis shoes with a flexible Bounce midsole, breathable mesh upper, and recycled materials.',
                'description'       => "Tennis shoes for slick play on all surfaces, made in part with recycled materials.\r\nLet your game shine through in these Court Spec 2 tennis shoes from adidas. With a rubber, all-court outsole and flexible Bounce midsole, these lightweight shoes provide solid performance on any surface. Breathable mesh and synthetic overlays team up for a classic-looking upper that'll keep you comfortable through intense rallies.\r\n\r\nThis product features at least 20% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make.",
                'regular_price'     => 60.72,
                'sale_price'        => 37.94,
                'SKU'               => 'MSH-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779782060.jpg',
                'images'            => '1779782060-1.jpg,1779782060-2.jpg,1779782060-3.jpg',
                'category_id'       => 7,
                'brand_id'          => 5,
                'created_at'        => '2026-05-26 00:54:23',
                'updated_at'        => '2026-05-26 00:54:23',
            ],
            [
                'id'                => 18,
                'name'              => 'CourtJam Control 3 Tennis Shoes',
                'slug'              => 'courtjam-control-3-tennis-shoes',
                'short_description' => 'Comfortable adidas tennis shoes with a Bounce midsole, breathable mesh upper, and durable hard court outsole.',
                'description'       => "Comfortable tennis shoes for owning the court, made in part with recycled materials.\r\nStep into your next match with the comfort and control of these adidas tennis shoes. Their flexible Bounce midsole will keep you on your toes while Torsion System helps you translate instinct into quick cuts and slides. Sitting on a specialist hard court outsole, the mesh upper keeps your feet cool when everything's on the line.\r\n\r\nThis product features at least 20% recycled materials. By reusing materials that have already been created, we help to reduce waste and our reliance on finite resources and reduce the footprint of the products we make.",
                'regular_price'     => 95.00,
                'sale_price'        => null,
                'SKU'               => 'MSH-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 1,
                'image'             => '1779782261.jpg',
                'images'            => '1779782261-1.jpg,1779782261-2.jpg,1779782261-3.jpg,1779782261-4.jpg,1779782261-5.jpg',
                'category_id'       => 7,
                'brand_id'          => 5,
                'created_at'        => '2026-05-26 00:57:45',
                'updated_at'        => '2026-05-26 00:57:45',
            ],
            [
                'id'                => 19,
                'name'              => 'Chuck 70',
                'slug'              => 'chuck-70',
                'short_description' => 'Premium Chuck 70 high-top sneakers with vintage details, cushioned comfort, and a durable canvas upper.',
                'description'       => "By 1970, the Chuck Taylor All Star evolved into one of the best basketball sneakers, ever. The Chuck 70 celebrates that heritage by bringing together archival-inspired details with modern comfort updates. OthoLite insole cushioning and winged tongue stitching takes the comfort level up a notch. A glossy, egret midsole and signature star ankle patch brings out the shoe's iconic, vintage style. Updated in archival color on premium canvas.\r\n\r\nFeatures And Benefits\r\nHigh-top shoe with premium canvas upper in seasonal color\r\nWinged tongue stitching helps lock it in place\r\nVintage star ankle patch and license plate\r\nArchive-inspired, glossy egret midsole\r\nOthoLite insole cushioning",
                'regular_price'     => 87.85,
                'sale_price'        => null,
                'SKU'               => 'MSH-003',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 3,
                'image'             => '1779782462.jpg',
                'images'            => '1779782462-1.jpg,1779782462-2.jpg,1779782462-3.jpg,1779782462-4.jpg,1779782462-5.jpg',
                'category_id'       => 7,
                'brand_id'          => 7,
                'created_at'        => '2026-05-26 01:01:06',
                'updated_at'        => '2026-05-26 01:01:06',
            ],
            [
                'id'                => 20,
                'name'              => 'Chuck 70 Canvas & Suede',
                'slug'              => 'chuck-70-canvas-suede',
                'short_description' => 'Premium Chuck 70 sneakers with a canvas and suede upper, vintage details, and cushioned comfort.',
                'description'       => "The shoe you love. Re-crafted with premium canvas and suede.\r\n\r\nIn the early '70s, the Chuck Taylor got a makeover. Premium canvas. A varnished sole. Comfier cushioning. The cultural icon continues to evolve with suede overlays for an even more refined take that goes with just about everything.\r\n\r\nFeatures and Benefits\r\nDurable canvas upper with suede overlays for that structured Chuck 70 look and feel\r\nOrthoLite cushioning helps provide optimal underfoot comfort\r\nVarnished, off-white midsole and toe cap for a vintage vibe\r\nThick cotton laces add a premium touch\r\nSignature All Star license plate",
                'regular_price'     => 87.00,
                'sale_price'        => 61.10,
                'SKU'               => 'MSH-004',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779783138.jpg',
                'images'            => '1779783138-1.jpg,1779783138-2.jpg,1779783138-3.jpg,1779783138-4.jpg,1779783138-5.jpg',
                'category_id'       => 7,
                'brand_id'          => 7,
                'created_at'        => '2026-05-26 01:12:20',
                'updated_at'        => '2026-05-26 01:12:20',
            ],
            [
                'id'                => 21,
                'name'              => 'Nike Pegasus Premium',
                'slug'              => 'nike-pegasus-premium',
                'short_description' => 'Nike Pegasus Premium running shoes with ZoomX, Air Zoom, and ReactX cushioning for lightweight comfort and energy return.',
                'description'       => "The Pegasus Premium supercharges responsive cushioning with a triple stack of our most powerful running technologies: ZoomX foam, a sculpted Air Zoom unit and ReactX foam. It's our most responsive Pegasus, providing high energy return unlike any other. With a lighter-than-air upper, it decreases weight and increases breathability so you can fly fast.\r\n\r\nColour Shown: Photon Dust/Black/Metallic Silver\r\nStyle: IR1229-001\r\nCountry/Region of Origin: Vietnam",
                'regular_price'     => 235.50,
                'sale_price'        => null,
                'SKU'               => 'MSH-004',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779783334.jpg',
                'images'            => '1779783334-1.jpg,1779783334-2.jpg,1779783334-3.jpg,1779783334-4.jpg,1779783334-5.jpg,1779783334-6.jpg,1779783334-7.jpg',
                'category_id'       => 7,
                'brand_id'          => 6,
                'created_at'        => '2026-05-26 01:15:38',
                'updated_at'        => '2026-05-26 01:15:38',
            ],
            [
                'id'                => 22,
                'name'              => 'OVERSIZED CHECKED SHIRT',
                'slug'              => 'oversized-checked-shirt',
                'short_description' => 'Oversized checked cotton shirt with a lightweight feel, pointed collar, and classic button-up design.',
                'description'       => 'An oversized buttoned checked shirt crafted from a lightweight cotton fabric. This classic go-to piece features a pointed collar, two buttons at each cuff, and a box pleat at the back.',
                'regular_price'     => 50.00,
                'sale_price'        => 41.00,
                'SKU'               => 'MS-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 2,
                'image'             => '1779783553.jpg',
                'images'            => '1779783553-1.jpg',
                'category_id'       => 3,
                'brand_id'          => 4,
                'created_at'        => '2026-05-26 01:19:14',
                'updated_at'        => '2026-05-26 01:19:14',
            ],
            [
                'id'                => 23,
                'name'              => 'RELAXED CHECKED LONG-SLEEVED SHIRT',
                'slug'              => 'relaxed-checked-long-sleeved-shirt',
                'short_description' => 'Loose-fit checked seersucker shirt in lightweight cotton with a pointed collar and button-up front.',
                'description'       => 'A long-sleeved checked shirt crafted from lightweight seersucker cotton, cut to a loose, relaxed fit. Designed with a pointed collar, a front button placket, and subtle knife pleats for added structure.',
                'regular_price'     => 50.00,
                'sale_price'        => 29.00,
                'SKU'               => 'MS-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 5,
                'image'             => '1779783633.jpg',
                'images'            => '1779783633-1.jpg',
                'category_id'       => 3,
                'brand_id'          => 4,
                'created_at'        => '2026-05-26 01:20:34',
                'updated_at'        => '2026-05-26 01:20:34',
            ],
            [
                'id'                => 24,
                'name'              => 'ANTI UNISEX LOW WAIST REGULAR STRAIGHT JEANS',
                'slug'              => 'anti-unisex-low-waist-regular-straight-jeans',
                'short_description' => 'Low-waist straight-leg jeans in rigid cotton denim with a regular fit and classic 5-pocket styling.',
                'description'       => 'Anti unisex jeans have a regular fit with a low waist, straight leg and long length. These jeans are crafted from rigid cotton denim enhanced with recycled cotton, featuring a classic 5-pocket design and a zip fly.',
                'regular_price'     => 59.99,
                'sale_price'        => null,
                'SKU'               => 'MJ-001',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779783835.jpg',
                'images'            => '1779783835-1.jpg,1779783835-2.jpg,1779783835-3.jpg,1779783835-4.jpg,1779783835-5.jpg',
                'category_id'       => 5,
                'brand_id'          => 2,
                'created_at'        => '2026-05-26 01:23:56',
                'updated_at'        => '2026-05-26 01:23:56',
            ],
            [
                'id'                => 25,
                'name'              => 'LOOSER REGULAR WAIST LOOSE STRAIGHT JEANS',
                'slug'              => 'looser-regular-waist-loose-straight-jeans',
                'short_description' => 'Loose-fit straight-leg jeans in rigid cotton denim with a regular waist and classic 5-pocket design.',
                'description'       => 'Looser jeans have a loose fit with a regular waist, straight leg and long length. These jeans are crafted from rigid cotton denim enhanced with recycled cotton, featuring a classic 5-pocket design and a zip fly.',
                'regular_price'     => 59.99,
                'sale_price'        => null,
                'SKU'               => 'MJ-002',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 4,
                'image'             => '1779783963.jpg',
                'images'            => '1779783963-1.jpg,1779783963-2.jpg,1779783963-3.jpg,1779783963-4.jpg,1779783963-5.jpg',
                'category_id'       => 5,
                'brand_id'          => 2,
                'created_at'        => '2026-05-26 01:26:05',
                'updated_at'        => '2026-05-26 01:26:05',
            ],
            [
                'id'                => 26,
                'name'              => 'ASTRO MID RISE LOOSE BAGGY UNISEX JEANS',
                'slug'              => 'astro-mid-rise-loose-baggy-unisex-jeans',
                'short_description' => 'Mid-rise baggy jeans in rigid organic cotton denim with a loose fit and oversized back pockets.',
                'description'       => 'A pair of mid-rise unisex jeans with a loose fit and baggy leg. These jeans are crafted from organic cotton rigid denim with recycled cotton. They feature a classic five-pocket design, large back pockets, and a button fly.',
                'regular_price'     => 69.99,
                'sale_price'        => null,
                'SKU'               => 'MJ-003',
                'stock_status'      => 'instock',
                'featured'          => 1,
                'quantity'          => 8,
                'image'             => '1779784130.jpg',
                'images'            => '1779784130-1.jpg,1779784130-2.jpg,1779784130-3.jpg,1779784130-4.jpg',
                'category_id'       => 5,
                'brand_id'          => 4,
                'created_at'        => '2026-05-26 01:28:51',
                'updated_at'        => '2026-05-26 01:28:51',
            ],
        ]);
    }
}
